language: node_js
node_js:
- 4.4.5
before_install:
- echo "before_install"
install:
- echo "install"
script:
- echo "script"
before_deploy:
- echo "before_deploy"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dir/*
  on:
    tags: true
after_deploy:
- echo "after_deploy"
